23 separat gamelogic from activities
se2-game-of-life/frontend pull request #26
Opened 2024-04-11 16:19 UTC by J0hanna01

The usernamecheck() has been moved to a separate class so that the game logic is separated from the activities.

2024-04-15 17:58 UTC, thomas-schleicher requested changes
I think that Player DTO should be used instead of the "User" and that the business logic of the Main Activity should be refactored to a View Model. Everything else looks good :)

2024-04-15 17:58 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/game/User.java
> +public class User {
I would suggest using the PlayerDTO as the "user" because it also stores the player name.

2024-04-15 17:58 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/game/User.java
> +    public boolean checkUsername(){
This logic should not be in here, create a MainViewModel.java file that extends View Model and do all the business logic associated with the Main Activity in there.

2024-04-15 19:07 UTC, J0hanna01 commented on app/src/main/java/se2/group3/gameoflife/frontend/game/User.java
> +    public boolean checkUsername(){
Great idea! I have now implemented this and also adapted the unit tests accordingly.

Thank you again. See you tomorrow! :)

2024-04-16 11:10 UTC, thomas-schleicher approved these changes

2024-04-16 11:13 UTC, Haxe33 approved these changes
lgtm!

2024-04-16 11:13 UTC, merged