Merge development into main
se2-game-of-life/frontend pull request #32
Opened 2024-04-23 17:36 UTC by J0hanna01

What has been changed?
*Game logic and server communication have been given their own classes (removed from the activities).
*Player DTO has been extended
*A draft for the player's first decision (College vs Career) has been added (communication to the server still needs to be added).

2024-04-24 08:47 UTC, thomas-schleicher requested changes

2024-04-24 08:47 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/activities/ChoosePathActivity.java
The college boolean should be in the ChoosePathViewModel if we stick to this design. However, I think this is a useless activity, if it only handles the ChoosePath, I think it should just be part of the GameActivity / GameViewModel.

2024-04-24 08:47 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/activities/MainActivity.java
> +    private static String username = null;
This should also probably be refactored into lobbyViewModel as a live data object.

2024-04-24 08:47 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/activities/StartGameActivity.java
> +        startGameViewModel.getLobby().observe(StartGameActivity.this, this::updateLobby);
The Activity should pass the DTO from the intent to the ViewModel for processing instead of processing the data by itself. Also error handling should be changed according to the desired execution process of the app.

2024-04-24 08:47 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/dto/PlayerDTO.java
> +        dest.writeString(playerName);
This method needs to have all the attributes of the player, not just the player name.

2024-04-24 08:47 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/viewmodels/ChoosePathViewModel.java
> +        //todo: communicate decision to server
Same as ChoosePathActivity, this might be redundant. Otherwise, this should include the decision making and send the appropriate message to the server.

2024-04-24 09:31 UTC, J0hanna01 commented on app/src/main/java/se2/group3/gameoflife/frontend/activities/ChoosePathActivity.java
Hei Thomas,
I have changed the ChoosePath.Activity to the first fragment of the GameActivity (previous BoardActivity). This means that we no longer have a separate activity for choose path.

2024-04-24 09:33 UTC, J0hanna01 commented on app/src/main/java/se2/group3/gameoflife/frontend/viewmodels/ChoosePathViewModel.java
> +        //todo: communicate decision to server
This method is now part of GameViewModel. (Unfortunately I haven't had time to implement it yet, but will do so this week).

2024-04-29 18:22 UTC, J0hanna01 commented
@thomas-schleicher thanks for your feedback! :) I adapted the code based on your requested changes. 👍

2024-05-12 14:51 UTC, thomas-schleicher approved these changes
LGTM

2024-05-12 14:57 UTC, merged