Refactor main
se2-game-of-life/frontend pull request #49
Opened 2024-05-26 12:34 UTC by J0hanna01

*delete duplicated methods
*Combine all ViewModels that are used for GameActvity (+ Fragments) into one GameViewModel.

2024-05-27 12:33 UTC, nzhurat approved these changes

2024-05-27 12:40 UTC, thomas-schleicher requested changes

2024-05-27 12:40 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/viewmodels/GameViewModel.java
> +    private final MutableLiveData<Integer> spinResult = new MutableLiveData<>();
This should be refactored/removed, the spin result is in the lobbyDTO and should be updated based on that.

2024-05-27 12:40 UTC, thomas-schleicher commented on app/src/main/java/se2/group3/gameoflife/frontend/viewmodels/GameViewModel.java
> +                            spinResult.setValue(lobbyDTO.getSpunNumber());
ˆˆ

2024-05-27 16:07 UTC, Haxe33 approved these changes

2024-05-28 08:37 UTC, thomas-schleicher approved these changes

2024-05-28 08:37 UTC, merged